resources:
- name: myScannedRepo
  type: GitRepo
  configuration:
    # Your JFrog integration with Github
    gitProvider: "jfrogPipeline"
    # Github repository
    path: "spectralpipeline/jfrogPipeline"
    branches:
      include: main
      
- name: cron_trigger
  type: CronTrigger
  configuration:
    interval: '0 0 * * *'

pipelines:
- name: Spectral
  steps:
    - name: SpectralScan
      type: Bash
      configuration:
          integrations:
              - name: spectraldsn
              - name: github
              - name: gitlab
              - name: spectralDevUrl
          inputResources:
              # - name: myScannedRepo
              - name: cron_trigger
      execution:
        onExecute:
          # - cd dependencyState/resources/myScannedRepo
          - curl -L "$int_spectralDevUrl_SPECTRAL_DEV_URL?dsn=$int_spectraldsn_SPECTRAL_DSN" | sh
          - SPECTRAL_DSN=$int_spectraldsn_SPECTRAL_DSN $HOME/.spectral/spectral github -k repo -t $int_github_MY_GITHUB_TOKEN https://github.com/ACME-Corp-Demo/test-infra --ok
          - SPECTRAL_DSN=$int_spectraldsn_SPECTRAL_DSN $HOME/.spectral/spectral gitlab -k repo -t $int_gitlab_MY_GITLAB_TOKEN https://gitlab.com/acme-corp-demo/test-infra --ok
