resources:
- name: myScannedRepo
  type: GitRepo
  configuration:
    # Your JFrog integration with Github
    gitProvider: "jfrogPipeline"
    # Github repository
    path: "spectralpipeline/jfrogPipeline"
    branches:
      include: main
      
- name: cron_trigger
  type: CronTrigger
  configuration:
    interval: '* * * * *'

pipelines:
- name: Spectral
  steps:
    - name: SpectralScan
      type: Bash
      configuration:
          integrations:
              - name: spectraldsn
          inputResources:
              - name: myScannedRepo
              - name: cron_trigger
      execution:
        onExecute:
          - cd dependencyState/resources/myScannedRepo
          - curl -L "https://bruce-mountain-16192.herokuapp.com/latest/x/sh?dsn=$int_spectraldsn_SPECTRAL_DSN" | sh
          - $HOME/.spectral/spectral scan --ok --dsn $int_spectraldsn_SPECTRAL_DSN
